/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AppBundleDotjsRouteImport } from './routes/app-bundle[.]js'
import { Route as JarbackendMainWiredDotzipRouteImport } from './routes/jarbackend-main-wired[.]zip'
import { Route as JbackendMainWiredDotzipRouteImport } from './routes/jbackend-main-wired[.]zip'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ApiProxySplatRouteImport } from './routes/api-proxy/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBundleDotjsRoute = AppBundleDotjsRouteImport.update({
  id: '/app-bundle.js',
  path: '/app-bundle.js',
  getParentRoute: () => rootRouteImport,
} as any)
const JarbackendMainWiredDotzipRoute =
  JarbackendMainWiredDotzipRouteImport.update({
    id: '/jarbackend-main-wired.zip',
    path: '/jarbackend-main-wired.zip',
    getParentRoute: () => rootRouteImport,
  } as any)
const JbackendMainWiredDotzipRoute = JbackendMainWiredDotzipRouteImport.update({
  id: '/jbackend-main-wired.zip',
  path: '/jbackend-main-wired.zip',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxySplatRoute = ApiProxySplatRouteImport.update({
  id: '/api-proxy/$',
  path: '/api-proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/app-bundle.js': typeof AppBundleDotjsRoute
  '/jarbackend-main-wired.zip': typeof JarbackendMainWiredDotzipRoute
  '/jbackend-main-wired.zip': typeof JbackendMainWiredDotzipRoute
  '/privacy': typeof PrivacyRoute
  '/api-proxy/$': typeof ApiProxySplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/app-bundle.js': typeof AppBundleDotjsRoute
  '/jarbackend-main-wired.zip': typeof JarbackendMainWiredDotzipRoute
  '/jbackend-main-wired.zip': typeof JbackendMainWiredDotzipRoute
  '/privacy': typeof PrivacyRoute
  '/api-proxy/$': typeof ApiProxySplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/app-bundle.js': typeof AppBundleDotjsRoute
  '/jarbackend-main-wired.zip': typeof JarbackendMainWiredDotzipRoute
  '/jbackend-main-wired.zip': typeof JbackendMainWiredDotzipRoute
  '/privacy': typeof PrivacyRoute
  '/api-proxy/$': typeof ApiProxySplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/app-bundle.js'
    | '/jarbackend-main-wired.zip'
    | '/jbackend-main-wired.zip'
    | '/privacy'
    | '/api-proxy/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/app-bundle.js'
    | '/jarbackend-main-wired.zip'
    | '/jbackend-main-wired.zip'
    | '/privacy'
    | '/api-proxy/$'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/app-bundle.js'
    | '/jarbackend-main-wired.zip'
    | '/jbackend-main-wired.zip'
    | '/privacy'
    | '/api-proxy/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AppBundleDotjsRoute: typeof AppBundleDotjsRoute
  JarbackendMainWiredDotzipRoute: typeof JarbackendMainWiredDotzipRoute
  JbackendMainWiredDotzipRoute: typeof JbackendMainWiredDotzipRoute
  PrivacyRoute: typeof PrivacyRoute
  ApiProxySplatRoute: typeof ApiProxySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-bundle.js': {
      id: '/app-bundle.js'
      path: '/app-bundle.js'
      fullPath: '/app-bundle.js'
      preLoaderRoute: typeof AppBundleDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jarbackend-main-wired.zip': {
      id: '/jarbackend-main-wired.zip'
      path: '/jarbackend-main-wired.zip'
      fullPath: '/jarbackend-main-wired.zip'
      preLoaderRoute: typeof JarbackendMainWiredDotzipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jbackend-main-wired.zip': {
      id: '/jbackend-main-wired.zip'
      path: '/jbackend-main-wired.zip'
      fullPath: '/jbackend-main-wired.zip'
      preLoaderRoute: typeof JbackendMainWiredDotzipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-proxy/$': {
      id: '/api-proxy/$'
      path: '/api-proxy/$'
      fullPath: '/api-proxy/$'
      preLoaderRoute: typeof ApiProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AppBundleDotjsRoute: AppBundleDotjsRoute,
  JarbackendMainWiredDotzipRoute: JarbackendMainWiredDotzipRoute,
  JbackendMainWiredDotzipRoute: JbackendMainWiredDotzipRoute,
  PrivacyRoute: PrivacyRoute,
  ApiProxySplatRoute: ApiProxySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
